### PR TITLE
Standardize use of throw bot.expections.

### LINKED ISSUE #67: Problems when executors from ext/types threw exceptions
Exceptions thrown by ext/types are being imported based on a different object compared with the expected exceptions in `core/controller.ts`;

For example when StringSearch receives an empty result from server it throws a `ValidatorError` extracted from YveBot.exceptions and then controller tries to analyse it by checking if it is an instance of `ValidatorError` from module `./exceptions`. This check results in a fail and then the bot get stuck :/

### PR DESCRIPTION
**Pull request by rafaelverger**
FIX #67

### CODE REVIEW

File: src/core/controller.ts [hunk 1]
```diff
@@ -221,10 +221,10 @@ export class Controller {
       answer = await this.executeRuleTypeExecutors(rule, message);
     } catch (e) {
       let expectedError = false;
-      if (e instanceof ValidatorError) {
+      if (e instanceof bot.exceptions.ValidatorError) {
```
Comment (andersonba) [inline src/core/controller.ts]: remove the imports used on top of the file
https://github.com/rafaelverger/yve-bot/blob/dfa576f9dfe051490ae54d2b05371c3c03e4cf1f/src/core/controller.ts#L3

and change all occurrences to use `bot.exceptions.X`

Comment (rafaelverger) [reply src/core/controller.ts]: nice!
