### PR TITLE
Fix bug in StringSearch execution after PauseException

### LINKED ISSUE #64: StringSearch type isn't working after selecting bubble from server's response
Some change from 1.9.0 to 1.10.0 that cause a malfunction on StringSearch
image

### PR DESCRIPTION
**Pull request by rafaelverger**
FIX #64

### CODE REVIEW

File: src/ext/types/StringSearch.ts [hunk 1]
```diff
@@ -44,6 +44,12 @@ export default YveBot.types.defineExtension('StringSearch', {
     },
     {
       transform: async (results: any, rule: IRule, bot: YveBot) => {
+        if (bot.store.get(`stringsearch.${rule.name}`)) {
```
Comment (andersonba) [inline src/ext/types/StringSearch.ts]: missing `.wait` key?

Comment (rafaelverger) [reply src/ext/types/StringSearch.ts]: It worked because ``bot.store.get(`stringsearch.${rule.name}`)`` returns `{ wait: true }` after first execution
